// Do not edit: This code was generated by flatdata's generator.
#![allow(
    clippy::manual_div_ceil,
    clippy::useless_attribute,
    clippy::useless_transmute
)]
#[allow(missing_docs)]
pub mod open_geocode {
    #[allow(unused_imports)]
    use flatdata::{flatdata_read_bytes, flatdata_write_bytes};

    #[repr(transparent)]
    #[derive(Clone)]
    pub struct StoredRecord {
        data: [u8; 238],
    }

    impl StoredRecord {
        /// Unsafe since the struct might not be self-contained
        pub unsafe fn new_unchecked() -> Self {
            Self { data: [0; 238] }
        }
    }

    impl flatdata::Struct for StoredRecord {
        unsafe fn create_unchecked() -> Self {
            Self { data: [0; 238] }
        }

        const SIZE_IN_BYTES: usize = 238;
        const IS_OVERLAPPING_WITH_NEXT: bool = false;
    }

    impl StoredRecord {
        pub fn new() -> Self {
            Self { data: [0; 238] }
        }

        /// Create reference from byte array of matching size
        pub fn from_bytes(data: &[u8; 238]) -> &Self {
            // Safety: This is safe since StoredRecord is repr(transparent)
            unsafe { std::mem::transmute(data) }
        }

        /// Create reference from byte array of matching size
        pub fn from_bytes_mut(data: &mut [u8; 238]) -> &mut Self {
            // Safety: This is safe since StoredRecord is repr(transparent)
            unsafe { std::mem::transmute(data) }
        }

        /// Create reference from byte array
        pub fn from_bytes_slice(data: &[u8]) -> Result<&Self, flatdata::ResourceStorageError> {
            // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
            if data.len() < 238 {
                assert_eq!(data.len(), 238);
                return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
            }
            let ptr = data.as_ptr() as *const [u8; 238];
            // Safety: We checked length before
            Ok(Self::from_bytes(unsafe { &*ptr }))
        }

        /// Create reference from byte array
        pub fn from_bytes_slice_mut(
            data: &mut [u8],
        ) -> Result<&mut Self, flatdata::ResourceStorageError> {
            // We cannot rely on TryFrom here, since it does not yet support > 33 bytes
            if data.len() < 238 {
                assert_eq!(data.len(), 238);
                return Err(flatdata::ResourceStorageError::UnexpectedDataSize);
            }
            let ptr = data.as_ptr() as *mut [u8; 238];
            // Safety: We checked length before
            Ok(Self::from_bytes_mut(unsafe { &mut *ptr }))
        }

        pub fn as_bytes(&self) -> &[u8; 238] {
            &self.data
        }
    }

    impl Default for StoredRecord {
        fn default() -> Self {
            Self::new()
        }
    }

    unsafe impl flatdata::NoOverlap for StoredRecord {}

    impl StoredRecord {
        #[inline]
        pub fn layer(&self) -> super::open_geocode::RecordLayer {
            let value = flatdata_read_bytes!(u8, self.data.as_ptr(), 0, 4);
            unsafe { std::mem::transmute::<u8, super::open_geocode::RecordLayer>(value) }
        }

        #[inline]
        pub fn source_object(&self) -> super::open_geocode::SourceObject {
            let value = flatdata_read_bytes!(u8, self.data.as_ptr(), 4, 2);
            unsafe { std::mem::transmute::<u8, super::open_geocode::SourceObject>(value) }
        }

        #[inline]
        pub fn geometry_type(&self) -> super::open_geocode::GeometryType {
            let value = flatdata_read_bytes!(u8, self.data.as_ptr(), 6, 2);
            unsafe { std::mem::transmute::<u8, super::open_geocode::GeometryType>(value) }
        }

        #[inline]
        pub fn location_precision(&self) -> super::open_geocode::LocationPrecisionCode {
            let value = flatdata_read_bytes!(u8, self.data.as_ptr(), 8, 2);
            unsafe { std::mem::transmute::<u8, super::open_geocode::LocationPrecisionCode>(value) }
        }

        #[inline]
        pub fn reserved(&self) -> u8 {
            let value = flatdata_read_bytes!(u8, self.data.as_ptr(), 10, 6);
            unsafe { std::mem::transmute::<u8, u8>(value) }
        }

        #[inline]
        pub fn source_object_id(&self) -> i64 {
            let value = flatdata_read_bytes!(i64, self.data.as_ptr(), 16, 64);
            unsafe { std::mem::transmute::<i64, i64>(value) }
        }

        #[inline]
        pub fn derived_record_count(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 80, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn display_lon(&self) -> i64 {
            let value = flatdata_read_bytes!(i64, self.data.as_ptr(), 144, 64);
            unsafe { std::mem::transmute::<i64, i64>(value) }
        }

        #[inline]
        pub fn display_lat(&self) -> i64 {
            let value = flatdata_read_bytes!(i64, self.data.as_ptr(), 208, 64);
            unsafe { std::mem::transmute::<i64, i64>(value) }
        }

        #[inline]
        pub fn interpolation_start(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 272, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn interpolation_end(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 304, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn interpolation_step(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 336, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn id_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 368, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn id_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 432, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn label_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 464, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn label_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 528, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn name_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 560, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn name_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 624, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn number_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 656, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn number_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 720, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn street_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 752, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn street_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 816, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn place_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 848, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn place_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 912, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn unit_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 944, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn unit_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1008, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn locality_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1040, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn locality_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1104, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn region_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1136, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn region_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1200, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn postcode_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1232, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn postcode_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1296, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn country_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1328, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn country_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1392, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn place_type_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1424, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn place_type_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1488, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn interpolation_type_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1520, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn interpolation_type_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1584, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn anchor_ids_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1616, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn anchor_ids_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1680, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn derived_from_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1712, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn derived_from_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1776, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }

        #[inline]
        pub fn geometry_start(&self) -> u64 {
            let value = flatdata_read_bytes!(u64, self.data.as_ptr(), 1808, 64);
            unsafe { std::mem::transmute::<u64, u64>(value) }
        }

        #[inline]
        pub fn geometry_len(&self) -> u32 {
            let value = flatdata_read_bytes!(u32, self.data.as_ptr(), 1872, 32);
            unsafe { std::mem::transmute::<u32, u32>(value) }
        }
    }

    impl std::fmt::Debug for StoredRecord {
        fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
            f.debug_struct("StoredRecord")
                .field("layer", &self.layer())
                .field("source_object", &self.source_object())
                .field("geometry_type", &self.geometry_type())
                .field("location_precision", &self.location_precision())
                .field("reserved", &self.reserved())
                .field("source_object_id", &self.source_object_id())
                .field("derived_record_count", &self.derived_record_count())
                .field("display_lon", &self.display_lon())
                .field("display_lat", &self.display_lat())
                .field("interpolation_start", &self.interpolation_start())
                .field("interpolation_end", &self.interpolation_end())
                .field("interpolation_step", &self.interpolation_step())
                .field("id_start", &self.id_start())
                .field("id_len", &self.id_len())
                .field("label_start", &self.label_start())
                .field("label_len", &self.label_len())
                .field("name_start", &self.name_start())
                .field("name_len", &self.name_len())
                .field("number_start", &self.number_start())
                .field("number_len", &self.number_len())
                .field("street_start", &self.street_start())
                .field("street_len", &self.street_len())
                .field("place_start", &self.place_start())
                .field("place_len", &self.place_len())
                .field("unit_start", &self.unit_start())
                .field("unit_len", &self.unit_len())
                .field("locality_start", &self.locality_start())
                .field("locality_len", &self.locality_len())
                .field("region_start", &self.region_start())
                .field("region_len", &self.region_len())
                .field("postcode_start", &self.postcode_start())
                .field("postcode_len", &self.postcode_len())
                .field("country_start", &self.country_start())
                .field("country_len", &self.country_len())
                .field("place_type_start", &self.place_type_start())
                .field("place_type_len", &self.place_type_len())
                .field("interpolation_type_start", &self.interpolation_type_start())
                .field("interpolation_type_len", &self.interpolation_type_len())
                .field("anchor_ids_start", &self.anchor_ids_start())
                .field("anchor_ids_len", &self.anchor_ids_len())
                .field("derived_from_start", &self.derived_from_start())
                .field("derived_from_len", &self.derived_from_len())
                .field("geometry_start", &self.geometry_start())
                .field("geometry_len", &self.geometry_len())
                .finish()
        }
    }

    impl std::cmp::PartialEq for StoredRecord {
        #[inline]
        fn eq(&self, other: &Self) -> bool {
            self.layer() == other.layer()
                && self.source_object() == other.source_object()
                && self.geometry_type() == other.geometry_type()
                && self.location_precision() == other.location_precision()
                && self.reserved() == other.reserved()
                && self.source_object_id() == other.source_object_id()
                && self.derived_record_count() == other.derived_record_count()
                && self.display_lon() == other.display_lon()
                && self.display_lat() == other.display_lat()
                && self.interpolation_start() == other.interpolation_start()
                && self.interpolation_end() == other.interpolation_end()
                && self.interpolation_step() == other.interpolation_step()
                && self.id_start() == other.id_start()
                && self.id_len() == other.id_len()
                && self.label_start() == other.label_start()
                && self.label_len() == other.label_len()
                && self.name_start() == other.name_start()
                && self.name_len() == other.name_len()
                && self.number_start() == other.number_start()
                && self.number_len() == other.number_len()
                && self.street_start() == other.street_start()
                && self.street_len() == other.street_len()
                && self.place_start() == other.place_start()
                && self.place_len() == other.place_len()
                && self.unit_start() == other.unit_start()
                && self.unit_len() == other.unit_len()
                && self.locality_start() == other.locality_start()
                && self.locality_len() == other.locality_len()
                && self.region_start() == other.region_start()
                && self.region_len() == other.region_len()
                && self.postcode_start() == other.postcode_start()
                && self.postcode_len() == other.postcode_len()
                && self.country_start() == other.country_start()
                && self.country_len() == other.country_len()
                && self.place_type_start() == other.place_type_start()
                && self.place_type_len() == other.place_type_len()
                && self.interpolation_type_start() == other.interpolation_type_start()
                && self.interpolation_type_len() == other.interpolation_type_len()
                && self.anchor_ids_start() == other.anchor_ids_start()
                && self.anchor_ids_len() == other.anchor_ids_len()
                && self.derived_from_start() == other.derived_from_start()
                && self.derived_from_len() == other.derived_from_len()
                && self.geometry_start() == other.geometry_start()
                && self.geometry_len() == other.geometry_len()
        }
    }

    impl StoredRecord {
        #[inline]
        #[allow(missing_docs)]
        pub fn set_layer(&mut self, value: super::open_geocode::RecordLayer) {
            flatdata_write_bytes!(u8; value, self.data, 0, 4)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_source_object(&mut self, value: super::open_geocode::SourceObject) {
            flatdata_write_bytes!(u8; value, self.data, 4, 2)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_geometry_type(&mut self, value: super::open_geocode::GeometryType) {
            flatdata_write_bytes!(u8; value, self.data, 6, 2)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_location_precision(
            &mut self,
            value: super::open_geocode::LocationPrecisionCode,
        ) {
            flatdata_write_bytes!(u8; value, self.data, 8, 2)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_reserved(&mut self, value: u8) {
            flatdata_write_bytes!(u8; value, self.data, 10, 6)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_source_object_id(&mut self, value: i64) {
            flatdata_write_bytes!(i64; value, self.data, 16, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_derived_record_count(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 80, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_display_lon(&mut self, value: i64) {
            flatdata_write_bytes!(i64; value, self.data, 144, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_display_lat(&mut self, value: i64) {
            flatdata_write_bytes!(i64; value, self.data, 208, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_interpolation_start(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 272, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_interpolation_end(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 304, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_interpolation_step(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 336, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_id_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 368, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_id_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 432, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_label_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 464, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_label_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 528, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_name_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 560, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_name_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 624, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_number_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 656, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_number_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 720, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_street_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 752, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_street_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 816, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_place_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 848, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_place_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 912, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_unit_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 944, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_unit_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1008, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_locality_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1040, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_locality_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1104, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_region_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1136, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_region_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1200, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_postcode_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1232, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_postcode_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1296, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_country_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1328, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_country_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1392, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_place_type_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1424, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_place_type_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1488, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_interpolation_type_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1520, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_interpolation_type_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1584, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_anchor_ids_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1616, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_anchor_ids_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1680, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_derived_from_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1712, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_derived_from_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1776, 32)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_geometry_start(&mut self, value: u64) {
            flatdata_write_bytes!(u64; value, self.data, 1808, 64)
        }

        #[inline]
        #[allow(missing_docs)]
        pub fn set_geometry_len(&mut self, value: u32) {
            flatdata_write_bytes!(u32; value, self.data, 1872, 32)
        }

        /// Copies the data from `other` into this struct.
        #[inline]
        pub fn fill_from(&mut self, other: &StoredRecord) {
            self.set_layer(other.layer());
            self.set_source_object(other.source_object());
            self.set_geometry_type(other.geometry_type());
            self.set_location_precision(other.location_precision());
            self.set_reserved(other.reserved());
            self.set_source_object_id(other.source_object_id());
            self.set_derived_record_count(other.derived_record_count());
            self.set_display_lon(other.display_lon());
            self.set_display_lat(other.display_lat());
            self.set_interpolation_start(other.interpolation_start());
            self.set_interpolation_end(other.interpolation_end());
            self.set_interpolation_step(other.interpolation_step());
            self.set_id_start(other.id_start());
            self.set_id_len(other.id_len());
            self.set_label_start(other.label_start());
            self.set_label_len(other.label_len());
            self.set_name_start(other.name_start());
            self.set_name_len(other.name_len());
            self.set_number_start(other.number_start());
            self.set_number_len(other.number_len());
            self.set_street_start(other.street_start());
            self.set_street_len(other.street_len());
            self.set_place_start(other.place_start());
            self.set_place_len(other.place_len());
            self.set_unit_start(other.unit_start());
            self.set_unit_len(other.unit_len());
            self.set_locality_start(other.locality_start());
            self.set_locality_len(other.locality_len());
            self.set_region_start(other.region_start());
            self.set_region_len(other.region_len());
            self.set_postcode_start(other.postcode_start());
            self.set_postcode_len(other.postcode_len());
            self.set_country_start(other.country_start());
            self.set_country_len(other.country_len());
            self.set_place_type_start(other.place_type_start());
            self.set_place_type_len(other.place_type_len());
            self.set_interpolation_type_start(other.interpolation_type_start());
            self.set_interpolation_type_len(other.interpolation_type_len());
            self.set_anchor_ids_start(other.anchor_ids_start());
            self.set_anchor_ids_len(other.anchor_ids_len());
            self.set_derived_from_start(other.derived_from_start());
            self.set_derived_from_len(other.derived_from_len());
            self.set_geometry_start(other.geometry_start());
            self.set_geometry_len(other.geometry_len());
        }
    }
    #[derive(Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum RecordLayer {
        Address = 0,
        Country = 1,
        District = 2,
        Interpolation = 3,
        Locality = 4,
        Neighbourhood = 5,
        Place = 6,
        Postcode = 7,
        Region = 8,
        Street = 9,
        #[doc(hidden)]
        UnknownValue10 = 10,
        #[doc(hidden)]
        UnknownValue11 = 11,
        #[doc(hidden)]
        UnknownValue12 = 12,
        #[doc(hidden)]
        UnknownValue13 = 13,
        #[doc(hidden)]
        UnknownValue14 = 14,
        #[doc(hidden)]
        UnknownValue15 = 15,
    }

    impl flatdata::helper::Int for RecordLayer {
        const IS_SIGNED: bool = false;
    }
    #[derive(Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum SourceObject {
        Node = 0,
        Way = 1,
        Relation = 2,
        Derived = 3,
    }

    impl flatdata::helper::Int for SourceObject {
        const IS_SIGNED: bool = false;
    }
    #[derive(Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum GeometryType {
        Point = 0,
        Linestring = 1,
        #[doc(hidden)]
        UnknownValue2 = 2,
        #[doc(hidden)]
        UnknownValue3 = 3,
    }

    impl flatdata::helper::Int for GeometryType {
        const IS_SIGNED: bool = false;
    }
    #[derive(Debug, PartialEq, Eq)]
    #[repr(u8)]
    pub enum LocationPrecisionCode {
        Point = 0,
        Centroid = 1,
        #[doc(hidden)]
        UnknownValue2 = 2,
        #[doc(hidden)]
        UnknownValue3 = 3,
    }

    impl flatdata::helper::Int for LocationPrecisionCode {
        const IS_SIGNED: bool = false;
    }

    #[derive(Clone)]
    pub struct RecordsArchive {
        _storage: flatdata::StorageHandle,
        records: &'static [super::open_geocode::StoredRecord],
        strings: flatdata::RawData<'static>,
        geometries: flatdata::RawData<'static>,
    }

    impl RecordsArchive {
        fn signature_name(archive_name: &str) -> String {
            format!("{}.archive", archive_name)
        }

        #[inline]
        pub fn records(&self) -> &[super::open_geocode::StoredRecord] {
            self.records
        }

        #[inline]
        pub fn strings(&self) -> flatdata::RawData {
            self.strings
        }

        #[inline]
        pub fn geometries(&self) -> flatdata::RawData {
            self.geometries
        }
    }

    impl ::std::fmt::Debug for RecordsArchive {
        fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
            f.debug_struct("RecordsArchive")
                .field("records", &self.records())
                .field("strings", &self.strings())
                .field("geometries", &self.geometries())
                .finish()
        }
    }

    impl RecordsArchive {
        pub fn open(
            storage: flatdata::StorageHandle,
        ) -> ::std::result::Result<Self, flatdata::ResourceStorageError> {
            #[allow(unused_variables)]
            use flatdata::ResourceStorageError as Error;
            #[allow(unused_imports)]
            use flatdata::SliceExt;
            // extend lifetime since Rust cannot know that we reference a cache here
            #[allow(unused_variables)]
            let extend = |x: Result<&[u8], Error>| -> Result<&'static [u8], Error> {
                x.map(|x| unsafe { std::mem::transmute(x) })
            };

            storage.read(
                &Self::signature_name("RecordsArchive"),
                schema::records_archive::RECORDS_ARCHIVE,
            )?;

            let records = {
                use flatdata::check_resource as check;
                let max_size = None;
                let resource =
                    extend(storage.read("records", schema::records_archive::resources::RECORDS));
                check(
                    "records",
                    |r| r.len(),
                    max_size,
                    resource.and_then(<&[super::open_geocode::StoredRecord]>::from_bytes),
                )?
            };
            let strings = {
                use flatdata::check_resource as check;
                let max_size = None;
                let resource =
                    extend(storage.read("strings", schema::records_archive::resources::STRINGS));
                check(
                    "strings",
                    |r| r.len(),
                    max_size,
                    resource.map(flatdata::RawData::new),
                )?
            };
            let geometries = {
                use flatdata::check_resource as check;
                let max_size = None;
                let resource = extend(
                    storage.read("geometries", schema::records_archive::resources::GEOMETRIES),
                );
                check(
                    "geometries",
                    |r| r.len(),
                    max_size,
                    resource.map(flatdata::RawData::new),
                )?
            };

            Ok(Self {
                _storage: storage,
                records,
                strings,
                geometries,
            })
        }
    }

    /// Builder for creating [`RecordsArchive`] archives.
    ///
    ///[`RecordsArchive`]: struct.RecordsArchive.html
    #[derive(Clone, Debug)]
    pub struct RecordsArchiveBuilder {
        storage: flatdata::StorageHandle,
    }

    impl RecordsArchiveBuilder {
        #[inline]
        /// Stores [`records`] in the archive.
        ///
        /// [`records`]: struct.RecordsArchive.html#method.records
        pub fn set_records(
            &self,
            vector: &[super::open_geocode::StoredRecord],
        ) -> ::std::io::Result<()> {
            use flatdata::SliceExt;
            self.storage.write(
                "records",
                schema::records_archive::resources::RECORDS,
                vector.as_bytes(),
            )
        }

        /// Opens [`records`] in the archive for buffered writing.
        ///
        /// Elements can be added to the vector until the [`ExternalVector::close`] method
        /// is called. To flush the data fully into the archive, this method must be called
        /// in the end.
        ///
        /// [`records`]: struct.RecordsArchive.html#method.records
        /// [`ExternalVector::close`]: flatdata/struct.ExternalVector.html#method.close
        #[inline]
        pub fn start_records(
            &self,
        ) -> ::std::io::Result<flatdata::ExternalVector<super::open_geocode::StoredRecord>>
        {
            flatdata::create_external_vector(
                &*self.storage,
                "records",
                schema::records_archive::resources::RECORDS,
            )
        }

        /// Stores [`strings`] in the archive.
        ///
        /// [`strings`]: struct.RecordsArchive.html#method.strings
        #[inline]
        pub fn set_strings(&self, data: &[u8]) -> ::std::io::Result<()> {
            self.storage
                .write("strings", schema::records_archive::resources::STRINGS, data)
        }

        /// Stores [`geometries`] in the archive.
        ///
        /// [`geometries`]: struct.RecordsArchive.html#method.geometries
        #[inline]
        pub fn set_geometries(&self, data: &[u8]) -> ::std::io::Result<()> {
            self.storage.write(
                "geometries",
                schema::records_archive::resources::GEOMETRIES,
                data,
            )
        }
    }

    impl RecordsArchiveBuilder {
        pub fn new(
            storage: flatdata::StorageHandle,
        ) -> Result<Self, flatdata::ResourceStorageError> {
            flatdata::create_archive(
                "RecordsArchive",
                schema::records_archive::RECORDS_ARCHIVE,
                &storage,
            )?;
            Ok(Self { storage })
        }
    }

    #[doc(hidden)]
    pub mod schema {
        pub mod records_archive {

            pub const RECORDS_ARCHIVE: &str = r#"namespace open_geocode {
enum RecordLayer : u8 : 4
{
    Address = 0,
    Country = 1,
    District = 2,
    Interpolation = 3,
    Locality = 4,
    Neighbourhood = 5,
    Place = 6,
    Postcode = 7,
    Region = 8,
    Street = 9,
}
}

namespace open_geocode {
enum SourceObject : u8 : 2
{
    Node = 0,
    Way = 1,
    Relation = 2,
    Derived = 3,
}
}

namespace open_geocode {
enum GeometryType : u8 : 2
{
    Point = 0,
    LineString = 1,
}
}

namespace open_geocode {
enum LocationPrecisionCode : u8 : 2
{
    Point = 0,
    Centroid = 1,
}
}

namespace open_geocode {
struct StoredRecord
{
    layer : .open_geocode.RecordLayer : 4;
    source_object : .open_geocode.SourceObject : 2;
    geometry_type : .open_geocode.GeometryType : 2;
    location_precision : .open_geocode.LocationPrecisionCode : 2;
    reserved : u8 : 6;
    source_object_id : i64 : 64;
    derived_record_count : u64 : 64;
    display_lon : i64 : 64;
    display_lat : i64 : 64;
    interpolation_start : u32 : 32;
    interpolation_end : u32 : 32;
    interpolation_step : u32 : 32;
    id_start : u64 : 64;
    id_len : u32 : 32;
    label_start : u64 : 64;
    label_len : u32 : 32;
    name_start : u64 : 64;
    name_len : u32 : 32;
    number_start : u64 : 64;
    number_len : u32 : 32;
    street_start : u64 : 64;
    street_len : u32 : 32;
    place_start : u64 : 64;
    place_len : u32 : 32;
    unit_start : u64 : 64;
    unit_len : u32 : 32;
    locality_start : u64 : 64;
    locality_len : u32 : 32;
    region_start : u64 : 64;
    region_len : u32 : 32;
    postcode_start : u64 : 64;
    postcode_len : u32 : 32;
    country_start : u64 : 64;
    country_len : u32 : 32;
    place_type_start : u64 : 64;
    place_type_len : u32 : 32;
    interpolation_type_start : u64 : 64;
    interpolation_type_len : u32 : 32;
    anchor_ids_start : u64 : 64;
    anchor_ids_len : u32 : 32;
    derived_from_start : u64 : 64;
    derived_from_len : u32 : 32;
    geometry_start : u64 : 64;
    geometry_len : u32 : 32;
}
}

namespace open_geocode {
archive RecordsArchive
{
    records : vector< .open_geocode.StoredRecord >;
    strings : raw_data;
    geometries : raw_data;
}
}

"#;

            pub mod resources {
                pub const RECORDS: &str = r#"namespace open_geocode {
enum RecordLayer : u8 : 4
{
    Address = 0,
    Country = 1,
    District = 2,
    Interpolation = 3,
    Locality = 4,
    Neighbourhood = 5,
    Place = 6,
    Postcode = 7,
    Region = 8,
    Street = 9,
}
}

namespace open_geocode {
enum SourceObject : u8 : 2
{
    Node = 0,
    Way = 1,
    Relation = 2,
    Derived = 3,
}
}

namespace open_geocode {
enum GeometryType : u8 : 2
{
    Point = 0,
    LineString = 1,
}
}

namespace open_geocode {
enum LocationPrecisionCode : u8 : 2
{
    Point = 0,
    Centroid = 1,
}
}

namespace open_geocode {
struct StoredRecord
{
    layer : .open_geocode.RecordLayer : 4;
    source_object : .open_geocode.SourceObject : 2;
    geometry_type : .open_geocode.GeometryType : 2;
    location_precision : .open_geocode.LocationPrecisionCode : 2;
    reserved : u8 : 6;
    source_object_id : i64 : 64;
    derived_record_count : u64 : 64;
    display_lon : i64 : 64;
    display_lat : i64 : 64;
    interpolation_start : u32 : 32;
    interpolation_end : u32 : 32;
    interpolation_step : u32 : 32;
    id_start : u64 : 64;
    id_len : u32 : 32;
    label_start : u64 : 64;
    label_len : u32 : 32;
    name_start : u64 : 64;
    name_len : u32 : 32;
    number_start : u64 : 64;
    number_len : u32 : 32;
    street_start : u64 : 64;
    street_len : u32 : 32;
    place_start : u64 : 64;
    place_len : u32 : 32;
    unit_start : u64 : 64;
    unit_len : u32 : 32;
    locality_start : u64 : 64;
    locality_len : u32 : 32;
    region_start : u64 : 64;
    region_len : u32 : 32;
    postcode_start : u64 : 64;
    postcode_len : u32 : 32;
    country_start : u64 : 64;
    country_len : u32 : 32;
    place_type_start : u64 : 64;
    place_type_len : u32 : 32;
    interpolation_type_start : u64 : 64;
    interpolation_type_len : u32 : 32;
    anchor_ids_start : u64 : 64;
    anchor_ids_len : u32 : 32;
    derived_from_start : u64 : 64;
    derived_from_len : u32 : 32;
    geometry_start : u64 : 64;
    geometry_len : u32 : 32;
}
}

namespace open_geocode {
archive RecordsArchive
{
    records : vector< .open_geocode.StoredRecord >;
}
}

"#;
                pub const STRINGS: &str = r#"namespace open_geocode {
archive RecordsArchive
{
    strings : raw_data;
}
}

"#;
                pub const GEOMETRIES: &str = r#"namespace open_geocode {
archive RecordsArchive
{
    geometries : raw_data;
}
}

"#;
            }
        }
    }
}
